#!/bin/bash
set -e

QWEN_CUSTOMVOICE_SPEAKER="${QWEN_CUSTOMVOICE_SPEAKER:-Ryan}"
QWEN_CUSTOMVOICE_INSTRUCT="${QWEN_CUSTOMVOICE_INSTRUCT:-}"
QWEN_CUSTOMVOICE_LANGUAGE="${QWEN_CUSTOMVOICE_LANGUAGE:-Auto}"
QWEN_CUSTOMVOICE_DEVICE="${QWEN_CUSTOMVOICE_DEVICE:-cuda:0}"
QWEN_CUSTOMVOICE_DTYPE="${QWEN_CUSTOMVOICE_DTYPE:-bfloat16}"
QWEN_CUSTOMVOICE_SAMPLES_PER_CHUNK="${QWEN_CUSTOMVOICE_SAMPLES_PER_CHUNK:-1024}"
QWEN_CUSTOMVOICE_CACHE_DIR="${QWEN_CUSTOMVOICE_CACHE_DIR:-/data/models}"
QWEN_CUSTOMVOICE_DEBUG="${QWEN_CUSTOMVOICE_DEBUG:-false}"

echo "Starting Wyoming Qwen3-TTS 1.7B CustomVoice server"
echo "Speaker: $QWEN_CUSTOMVOICE_SPEAKER"
echo "Language: $QWEN_CUSTOMVOICE_LANGUAGE"

CMD_ARGS=(
    "--uri" "tcp://0.0.0.0:10200"
    "--model" "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice"
    "--instruct" "$QWEN_CUSTOMVOICE_INSTRUCT"
    "--speaker" "$QWEN_CUSTOMVOICE_SPEAKER"
    "--language" "$QWEN_CUSTOMVOICE_LANGUAGE"
    "--device" "$QWEN_CUSTOMVOICE_DEVICE"
    "--dtype" "$QWEN_CUSTOMVOICE_DTYPE"
    "--samples-per-chunk" "$QWEN_CUSTOMVOICE_SAMPLES_PER_CHUNK"
    "--cache-dir" "$QWEN_CUSTOMVOICE_CACHE_DIR"
)

if [ "$QWEN_CUSTOMVOICE_DEBUG" = "true" ]; then
    CMD_ARGS+=("--debug")
fi

exec python3 /app/qwen_wrapper.py "${CMD_ARGS[@]}"
